import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class KeysService {

  private keys = [
    {
      id: 1,
      I: 'C',
      i: 'Cm',
      ii: 'Dm',
      iii: 'Em',
      IV: 'F',
      iv: 'Fm',
      V: 'G',
      Vsus4: 'Gsus4',
      V7: 'G7',
      bVI: 'Ab',
      vi: 'Am',
    },
    {
      id: 2,
      I: 'G',
      i: 'Gm',
      ii: 'Am',
      iii: 'Bm',
      IV: 'C',
      iv: 'Cm',
      V: 'D',
      Vsus4: 'Dsus4',
      V7: 'D7',
      bVI: 'Eb',
      vi: 'Em',
    },
    {
      id: 3,
      I: 'F',
      i: 'Fm',
      ii: 'Gm',
      iii: 'Am',
      IV: 'Bb',
      iv: 'Bbm',
      V: 'C',
      Vsus4: 'Csus4',
      V7: 'C7',
      bVI: 'Db',
      vi: 'Dm',
    },
    {
      id: 4,
      I: 'D',
      i: 'Dm',
      ii: 'Em',
      iii: 'Fsharpm',
      IV: 'G',
      iv: 'Gm',
      V: 'A',
      Vsus4: 'Asus4',
      V7: 'A7',
      bVI: 'Bb',
      vi: 'Bm',
    },
    {
      id: 5,
      I: 'Bb',
      i: 'Bbm',
      ii: 'Cm',
      iii: 'Dm',
      IV: 'Eb',
      iv: 'Ebm',
      V: 'F',
      Vsus4: 'Fsus4',
      V7: 'F7',
      bVI: 'Gb',
      vi: 'Gm',
    },
    {
      id: 6,
      I: 'A',
      i: 'Am',
      ii: 'Bm',
      iii: 'Csharpm',
      IV: 'D',
      iv: 'Dm',
      V: 'E',
      Vsus4: 'Esus4',
      V7: 'E7',
      bVI: 'F',
      vi: 'Fsharpm',
    },
    {
      id: 7,
      I: 'Eb',
      i: 'Ebm',
      ii: 'Fm',
      iii: 'Gm',
      IV: 'Ab',
      iv: 'Abm',
      V: 'Bb',
      Vsus4: 'Bbsus4',
      V7: 'Bb7',
      bVI: 'Cb',
      vi: 'Cm',
    },
    {
      id: 8,
      I: 'E',
      i: 'Em',
      ii: 'Fsharpm',
      iii: 'Gsharpm',
      IV: 'A',
      iv: 'Am',
      V: 'B',
      Vsus4: 'Bsus4',
      V7: 'B7',
      bVI: 'C',
      vi: 'Csharpm',
    },
    {
      id: 9,
      I: 'Ab',
      i: 'Abm',
      ii: 'Bbm',
      iii: 'Cm',
      IV: 'Db',
      iv: 'Dbm',
      V: 'Eb',
      Vsus4: 'Ebsus4',
      V7: 'Eb7',
      bVI: 'Fb',
      vi: 'Fm',
    },
    {
      id: 10,
      I: 'B',
      i: 'Bm',
      ii: 'Csharpm',
      iii: 'Dsharpm',
      IV: 'E',
      iv: 'Em',
      V: 'Fsharp',
      Vsus4: 'Fsharpsus4',
      V7: 'Fsharp7',
      bVI: 'G',
      vi: 'Gsharpm',
    },
  ];

  constructor() { }

  public getAll() {
    return this.keys;
  }
}
